version: "3.0"
services:
  web:
    image: prestashop/prestashop:latest
    volumes:
      - ./source:/var/www/html
    ports:
      - "80:80"
    external_links:
      - "mariadb:mysql"
    container_name: prestashop
    command: >
      bash -c "
      chown -R www-data:www-data /var/www/html &&
      chmod -R 755 /var/www/html &&
      apache2-foreground"

