<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVdcNY65\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVdcNY65/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerVdcNY65.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerVdcNY65\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerVdcNY65\appAppKernelProdContainer([
    'container.build_hash' => 'VdcNY65',
    'container.build_id' => '79d74e7b',
    'container.build_time' => 1716173478,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVdcNY65');
