<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPhLHRXq\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPhLHRXq/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerPhLHRXq.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerPhLHRXq\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerPhLHRXq\appAppKernelProdContainer([
    'container.build_hash' => 'PhLHRXq',
    'container.build_id' => '5718b591',
    'container.build_time' => 1712986677,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPhLHRXq');
