<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNwONemx\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNwONemx/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerNwONemx.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerNwONemx\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerNwONemx\appAppKernelProdContainer([
    'container.build_hash' => 'NwONemx',
    'container.build_id' => 'f88fa883',
    'container.build_time' => 1712986714,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNwONemx');
